//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnicalKnowledge
{
    using System;
    using System.Collections.Generic;
    
    public partial class Locacao
    {
        public int id_locacao { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> id_filme { get; set; }
        public Nullable<System.DateTime> devolucao { get; set; }
        public Nullable<System.DateTime> data_locacao { get; set; }
        public string observacao { get; set; }
        public Nullable<System.DateTime> estimativa_devolucao { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Filme Filme { get; set; }
    }
}
